CREATE TABLE IF NOT EXISTS CUSTOMER
(
    CUSTOMER_ID UUID        NOT NULL,
    NAME        VARCHAR(50) NOT NULL,
    CPF         VARCHAR(11) NOT NULL,
    CONSTRAINT CUSTOMER_TAB_PK PRIMARY KEY (CUSTOMER_ID),
    CONSTRAINT CUSTOMER_TAB_CPF_UK UNIQUE (CPF)
);

CREATE TABLE IF NOT EXISTS PRODUCT
(
    PRODUCT_ID  VARCHAR(25)      NOT NULL,
    NAME        VARCHAR(50)      NOT NULL,
    DESCRIPTION VARCHAR(100)     NOT NULL,
    PRICE       DOUBLE PRECISION NOT NULL,
    UNIT_MEAS   VARCHAR(3),
    CONSTRAINT PRODUCT_TAB_PK PRIMARY KEY (PRODUCT_ID)
);